### ISSUE TITLE
custom volumes don't work for server

### ISSUE THREAD

**Issue by shk3bq4d** [dj-wasabi/helm-zabbix#9]
Hello,

nice project! I hope you keep on the good work in there!

I believe that the custom volume code in the server template is incomplete, namely the integration of:

.Values.server.volumes
.Values.server.volumeMounts

I'll create a pull request.

Best regards!

**Comment by dj-wasabi** [comment]
Hi @shk3bq4d 

Thank you! Yes, it needs some more work. But currently a bit to much going right now. So hopefully soon I will be able to fully continue with this.

In the mean time, if you need a fix/functionality you can always create a PR.
